version: '3.7'
services:
  contacapp-node:
    image: contacapp-node
    build:
      context: ./
    working_dir: /home/node/app
    volumes:
      - type: bind
        source: ./
        target: /home/node/app
    container_name: contacapp-node
    networks:
      - contacapp-network
    ports:
      - "3000:3000"
    command: "npm start"
  #Mysql service
  contacapp-mysql:
    image: mysql
    volumes:
      - type: bind
        source: ./mysql/config
        target: /etc/mysql/conf.d
    container_name: contacapp-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=contacapp
      - MYSQL_USER=anthony
      - MYSQL_PASSWORD=secret
    networks:
      - contacapp-network

networks:
  contacapp-network:
    driver: bridge